/**
 * MGAPServerAdd_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ylxx.fx.utils;

public interface MGAPServerAdd_PortType extends java.rmi.Remote {
    public void MGAPAccRegisterChange(InPutHeadMsgList inPutHeadMsg, java.lang.String CUNO, javax.xml.rpc.holders.StringHolder CUAC, java.lang.String PTID, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder LCNO, javax.xml.rpc.holders.StringHolder TRDT, javax.xml.rpc.holders.StringHolder TRTM, javax.xml.rpc.holders.StringHolder PTNM) throws java.rmi.RemoteException;
    public void MGAPTransfer(InPutHeadMsgList inPutHeadMsg, javax.xml.rpc.holders.StringHolder CUAC, java.lang.String CYEN, javax.xml.rpc.holders.StringHolder SLAM, java.lang.String CUNO, java.lang.String TONM, javax.xml.rpc.holders.StringHolder TOAC, java.lang.String CATY, java.lang.String SCUNO, java.lang.String SNAME, java.lang.String TELO, java.lang.String POSTS, java.lang.String EXDB, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder LCNO, javax.xml.rpc.holders.StringHolder TRDT, javax.xml.rpc.holders.StringHolder TRTM, javax.xml.rpc.holders.StringHolder CBLV) throws java.rmi.RemoteException;
    public void MGAPTransferCancel(InPutHeadMsgList inPutHeadMsg, java.lang.String OTSN, java.lang.String OLDT, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder LCNO, javax.xml.rpc.holders.StringHolder TRDT, javax.xml.rpc.holders.StringHolder TRTM, javax.xml.rpc.holders.StringHolder CUAC, javax.xml.rpc.holders.StringHolder SLAM, javax.xml.rpc.holders.StringHolder TOAC, javax.xml.rpc.holders.StringHolder CBLV) throws java.rmi.RemoteException;
    public void MGAPBatchTransfer(InPutHeadMsgList inPutHeadMsg, java.lang.String BNUM, java.lang.String FILE, java.lang.String COUT, java.lang.String AMUT, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder LCNO, javax.xml.rpc.holders.StringHolder TRDT, javax.xml.rpc.holders.StringHolder TRTM) throws java.rmi.RemoteException;
    public void MGAPQueryBatchTransfer(InPutHeadMsgList inPutHeadMsg, javax.xml.rpc.holders.StringHolder BNUM, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder STAT, javax.xml.rpc.holders.StringHolder FILE, javax.xml.rpc.holders.StringHolder COUT, javax.xml.rpc.holders.StringHolder AMUT, javax.xml.rpc.holders.StringHolder SNUM, javax.xml.rpc.holders.StringHolder SSAM) throws java.rmi.RemoteException;
    public void MGAPQueryTransferHis(InPutHeadMsgList inPutHeadMsg, java.lang.String CUAC, java.lang.String STDT, java.lang.String EDDT, java.lang.String CYNM, java.lang.String TRFG, java.lang.String STAR, java.lang.String PNUM, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder COUNT, javax.xml.rpc.holders.StringHolder RNUM, OutQueryTransferHisListHolder outQueryTransferHisList) throws java.rmi.RemoteException;
    public void MGAPTradeForComp(InPutHeadMsgList inPutHeadMsg, java.lang.String CSOF, java.lang.String SOAC, java.lang.String CTOF, javax.xml.rpc.holders.StringHolder TOAC, javax.xml.rpc.holders.StringHolder SLNM, javax.xml.rpc.holders.StringHolder BYNM, javax.xml.rpc.holders.StringHolder BYAM, javax.xml.rpc.holders.StringHolder SLAM, java.lang.String AKPC, javax.xml.rpc.holders.StringHolder FVDA, java.lang.String EXDA, OutPutHeadMsgListHolder outPutHeadMsg, javax.xml.rpc.holders.StringHolder LCNO, javax.xml.rpc.holders.StringHolder TRDT, javax.xml.rpc.holders.StringHolder TRTM, javax.xml.rpc.holders.StringHolder EXPC, javax.xml.rpc.holders.StringHolder CBLV, javax.xml.rpc.holders.StringHolder AVPC) throws java.rmi.RemoteException;
}
